language: python

python:
  - 2.7

sudo: false

cache:
  apt: true
  pip: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.local

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-4.9
      - python-pip
      - graphviz      


install:
  - export PATH="$HOME/.local/bin:$PATH"
  - export FC=/usr/bin/gfortran-4.9
  - ln -fs /usr/bin/gfortran-4.9 "$HOME/.local/bin/gfortran" && gfortran --version
  - ls -l /usr/bin/gfortran-4.9
  - ln -fs /usr/bin/gcov-4.9 "$HOME/.local/bin/gcov" && gcov --version
  - pip install --upgrade graphviz
  - pip install --upgrade FoBiS.py
  - pip install --upgrade markdown-checklist 
  - pip install --upgrade ford
  - pip install --upgrade pybuilder
  - pip install --upgrade python-coveralls
  - pip install --upgrade pygooglechart
  - pyb install_dependencies --verbose

script:
  - pyb --verbose

after_success:
  - coveralls
