language: python

python:
  - 2.7
  - 3.4

before_install:
  - sudo apt-get install gfortran
  - pip install PreForM.py
  - pip install FoBiS.py

install:
  - pip install pybuilder
  - pyb install_dependencies --verbose
  - pip install python-coveralls

script:
  - pyb --verbose

after_success:
  - coveralls
